"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),root=path.join(__dirname,"..");
const ui=fs.readFileSync(path.join(root,"public/ui/baustellen-offer-builder.js"),"utf8"),server=fs.readFileSync(path.join(root,"server.js"),"utf8"),top=fs.readFileSync(path.join(root,"public/ui/topbar.js"),"utf8");
assert.match(top,/baustellen-offer-builder/);
for(const text of ["Kalkulation / Angebot","Regie + Material","Innenmalerei","Abdeckarbeiten – einmalig auswählen","Boden und Laufwege","Fassade","Fassadenfarbe 2x","Bad komplett","Fugenloses Bad","Terra Icon Unikatbelag","Kalkputz","Sumpfkalk-Wohlfühlputz","WDVS kurz","Isolierung kleben","Näherung: Bodenfläche × 3,5","Raum aus Länge / Breite / Höhe","Leistungsumfang / Räume","Mengen und Einheiten","Kalkulation dieser Position","Standard-Faktbox","Stundensatz","Materialaufschlag","Ab-/Zuschlag auf beides","Arbeitsschritt","Minuten","Material aus Stamm","Preis je Einheit","Verbrauch","Ergebnis"])assert.ok(ui.includes(text),`UI enthält ${text}`);
for(const text of ["offer-draft","coverSteps","bathroomSteps","bathroomCompactSteps","limeSteps","wdvsSteps","bathroomCalc","measurement","scopeDescription","showQuantities","laborHoursPerUnit","materialMarkupPct","adjustmentPct","workSteps","materials","hourlyRateOverridden"])assert.ok(server.includes(text),`Server enthält ${text}`);
for(const text of ["Räume und Aufmaß","Jeder Raum bildet eine eigene Gruppe","Näherung × 3,5","Exakt L/B/H","Leistungsfläche"])assert.ok(ui.includes(text),`Raumaufmaß enthält ${text}`);
assert.ok(ui.includes("Beschreibung der Leistung"),"Jeder Raum besitzt eine Leistungsbeschreibung");
assert.ok(ui.includes('"Wände + Decken"'),"Wand- und Deckenflächen werden gemeinsam angeboten");
assert.ok(ui.includes("function coverPosition()"),"Abdeckauswahl wird zu einer Position zusammengefasst");
for(const text of ["Preisstand:","Preise aktualisieren / neu kalkulieren","priceSnapshotAt"])assert.ok(ui.includes(text)||server.includes(text),`Preisstand enthält ${text}`);
for(const text of ["Material aus Regiestunden berechnen","Betrag je Stunde","Prozent vom Arbeitslohn","regieMaterialRate","regieMaterialMode"])assert.ok(ui.includes(text)||server.includes(text),`Regiematerial enthält ${text}`);
for(const text of ["ensureOfferMaterials","/admin/api/materials/auto","m.product||m.name"])assert.ok(ui.includes(text),`Automatische Materialübernahme enthält ${text}`);
assert.ok(server.includes("draft.rooms="),"Raumaufmaße werden serverseitig gespeichert");
console.log("OK: Angebotsbaukasten enthält Vorlagen, Detailkalkulation und Aufmaß je Raum.");
