"use strict";

const assert=require("assert");
const fs=require("fs");
const path=require("path");

const root=path.resolve(__dirname,"..");
const ui=fs.readFileSync(path.join(root,"public","ui","baustellen-live-hours.js"),"utf8");
const topbar=fs.readFileSync(path.join(root,"public","ui","topbar.js"),"utf8");
const baustellen=fs.readFileSync(path.join(root,"public","baustellen.html"),"utf8");
const leitstand=fs.readFileSync(path.join(root,"public","kristine.html"),"utf8");
assert.match(topbar,/baustellen-live-hours\.js\?v=20260910-project-archive-repair-4/);
assert.match(baustellen,/topbar\.js\?v=20260912-project-search-4/);
assert.match(leitstand,/timeEditorReleased=Boolean\(result\.released\)/);
assert.match(leitstand,/Produktiv · ohne Baustellenbezug/);
assert.match(leitstand,/Änderungen wirken nur auf die Mitarbeiterzeit/);
assert.match(leitstand,/\['Krank','Arzt','Urlaub','Sonderurlaub'\]/);
assert.doesNotMatch(ui,/if\(!token\)return null/);
assert.match(ui,/if\(token\)headers\["X-Krista-Token"\]=token/);
const server=fs.readFileSync(path.join(root,"server.js"),"utf8");
const brain=fs.readFileSync(path.join(root,"brain_outgoing_invoices.py"),"utf8");

assert.match(ui,/WW \/ KRISTINE Stundenabgleich/);
assert.match(ui,/WW jetzt abgleichen/);
assert.match(ui,/WinWorker-Daten/);
assert.match(ui,/KRISTINE-Daten/);
assert.match(ui,/data-hr-key/);
assert.match(ui,/als doppelt markieren/);
assert.match(ui,/hours-overlap/);
assert.match(ui,/hoursOverlapExcludedWwKeys/);
assert.match(ui,/Brain Connector liefert bereits produktive WW-Stunden/);
assert.doesNotMatch(ui,/Math\.max\(0,row\.hours-\.25\)/);
assert.match(ui,/pauseDeductionHours:num\(payload\.pauseDeductionHours\)/);
assert.match(ui,/personDayHours/);
for(const pair of [["mandi-faes","Manuel Faes"],["edi-mock","Edmund Mock"],["cathrin-grabherr","Cathrin Anna Grabherr"],["anna-cathrin-grabherr","Cathrin Anna Grabherr"],["cathrin-anna-grabherr","Cathrin Anna Grabherr"]])assert.ok(ui.includes(`"${pair[0]}":"${pair[1]}"`));
assert.match(ui,/person\.hours=Math\.max\(0,person\.hours-\.25\)/);
assert.match(ui,/return num\(liveByJob\.get\(String\(j\.jobId\)\)\?\.totalHours\)/);
assert.match(ui,/kristineTotal=Math\.max\(oldTotalHours\(j\),kristineDetailTotal\)/);
assert.match(ui,/actual=fusion\(j\)\.total/);
assert.match(ui,/IST inkl\. Regie/);
assert.match(ui,/bootstrap\?\.projectTimeArchive/);
assert.match(ui,/archivedPersonDays/);
assert.match(ui,/usableArchive/);
assert.match(ui,/for\(const released of usableArchive\)/);
assert.match(ui,/String\(segment\?\.type\|\|""\)!=="work"/);
assert.match(ui,/excluded=selectedExclusions/);
assert.match(ui,/person\.hours\*scale/);
assert.match(ui,/Auswahl geändert – bitte speichern/);
assert.match(ui,/Der Server hat die Auswahl nicht vollständig übernommen/);
assert.match(ui,/reconciliationDrafts\.get\(jobId\)\|\|selected/);
assert.match(ui,/✓ Auswahl gespeichert/);
assert.match(ui,/KRISTINE \+ \$\{hours\(fused\.ww\)\} WW/);
assert.match(ui,/Gesamtsumme nach Abgleich/);
assert.match(ui,/<details class="hr-details"/);
assert.match(ui,/Abgleichdetails anzeigen/);
assert.match(ui,/confirmed&&!dirty\?"":"open"/);
assert.doesNotMatch(ui,/confirm\(`/);
assert.doesNotMatch(ui,/prompt\(/);
assert.match(server,/app\.put\("\/admin\/api\/job\/:jobId\/hours-overlap"/);
assert.match(server,/cleanHoursOverlapKeys/);
assert.match(server,/hours_overlap_history_error/);
assert.match(brain,/"employeeName": str\(row\.get\("employeeName"\)/);
assert.match(brain,/"rows": detail_rows/);

console.log("baustellen live hours reconciliation test: ok");
