"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const hub = fs.readFileSync(path.join(root, "public", "ui", "baustellen-knowledge-hub.js"), "utf8");
const cockpit = fs.readFileSync(path.join(root, "public", "ui", "baustellen-cockpit.js"), "utf8");
const liveHours = fs.readFileSync(path.join(root, "public", "ui", "baustellen-live-hours.js"), "utf8");
const calculationGrid = fs.readFileSync(path.join(root, "public", "ui", "baustellen-calculation-grid-v2.js"), "utf8");
const chronik = fs.readFileSync(path.join(root, "public", "ui", "baustellen-chronik.js"), "utf8");
const server = fs.readFileSync(path.join(root, "server.js"), "utf8");
const preload = fs.readFileSync(path.join(root, "order-calculation-v2-preload.js"), "utf8");

assert.match(preload, /totalCalculatedHours = d\.calculatedHours \+ d\.plannedRegieHours/);
assert.match(preload, /sourcePlannedHours > 0/);
assert.match(preload, /\? number\(row\.plannedHours\) : 0/);
assert.match(hub, /fixedMaterialEk=material\*\.8,totalMaterialEk=fixedMaterialEk\+regieMaterialEk/);
assert.match(hub, /documentPerHour=actual>0\?documentNet\/actual:0/);
assert.match(hub, /gespeicherte \+ ausgestellte Rechnungen netto/);
assert.match(cockpit, /documents\.filter\(x=>x\?\.type==="regie_report"\)/);
assert.match(cockpit, /liveInvoiceNet=billedNet\+draftNet/);
assert.match(cockpit, /hasIssuedClosingInvoice=issuedInvoices\.some/);
assert.match(cockpit, /emailCount\+\(emailCount===1\?" E-Mail":" E-Mails"\)/);
assert.match(cockpit, /wwAdditionalHours=Math\.max\(0,actual-peopleHours\)/);
assert.match(cockpit, /WinWorker – zusätzlich/);
assert.match(cockpit, /Sollstunden gesamt/);
assert.match(cockpit, /Grundkalkulation \+ \$\{hours\(plannedRegie\)\} Regie\/Nachtrag/);
assert.match(cockpit, /Abrechenbar nach Reserve/);
assert.match(cockpit, /actual\*\(rate\+materialPerHour\)\*\.9/);
assert.match(cockpit, /openInvoice=draftNet>0\?draftNet:hasIssuedClosingInvoice\?0:Math\.max\(0,billableAfterReserve-billedNet\)/);
assert.match(cockpit, /Rechnungsentwurf gespeichert · noch nicht gedruckt\/ausgestellt/);
assert.match(cockpit, /Rechnung ausgestellt · nichts mehr abzurechnen/);
assert.match(liveHours, /reserve\.dataset\.bcSettled==="1"/);
assert.match(hub, /regieReportHours=String\(reportRegie\)/);
assert.match(liveHours, /function fusedPeople\(jobId\)/);
assert.match(liveHours, /function patchHoursTab\(id\)/);
assert.match(liveHours, /patchHoursTab\(id\)/);
assert.match(liveHours, /Produktive WW-Stempelstunden/);
assert.match(calculationGrid, /const totalTarget = target \+ plannedRegie/);
assert.match(calculationGrid, /set\("kcv2SumHours", hours\(totalTarget\)\)/);
assert.match(chronik, /function collectSurface\(regies,documents=\[\],metaRows=\[\]\)/);
assert.match(chronik, /function collectSurfacePeople\(regies,documents=\[\]\)/);
assert.match(chronik, /\/documentation`\)\.catch\(\(\)=>\(\{items:\[\]\}\)\)/);
assert.match(chronik, /data-bz-relevant/);
assert.match(chronik, /data-bz-save/);
assert.match(chronik, /data-bz-add-material/);
assert.match(chronik, /data-bz-create-material/);
assert.match(chronik, /custom:true,name/);
assert.match(chronik, /surface\.filter\(x=>x\.relevant\)/);
assert.match(chronik, /surface\.filter\(x=>!x\.relevant\)/);
assert.match(chronik, /<h4>Oberflächenrelevant<\/h4>/);
assert.match(chronik, /<h4>Material<\/h4>/);
assert.doesNotMatch(hub, /data-bk-tab="material"/);
assert.doesNotMatch(hub, /data-bk-panel="material"/);
assert.match(server, /custom: !!row\?\.custom/);
assert.match(server, /name: String\(row\?\.name/);
assert.match(server, /surfaceMaterialMeta: cleanSurfaceMaterialMeta/);

console.log("baustellen economy value tests passed");
