"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const hub = fs.readFileSync(path.join(root, "public", "ui", "baustellen-knowledge-hub.js"), "utf8");
const cockpit = fs.readFileSync(path.join(root, "public", "ui", "baustellen-cockpit.js"), "utf8");
const liveHours = fs.readFileSync(path.join(root, "public", "ui", "baustellen-live-hours.js"), "utf8");
const calculationGrid = fs.readFileSync(path.join(root, "public", "ui", "baustellen-calculation-grid-v2.js"), "utf8");
const calculationUi = fs.readFileSync(path.join(root, "public", "ui", "baustellen-calculation-v2.js"), "utf8");
const chronik = fs.readFileSync(path.join(root, "public", "ui", "baustellen-chronik.js"), "utf8");
const server = fs.readFileSync(path.join(root, "server.js"), "utf8");
const preload = fs.readFileSync(path.join(root, "order-calculation-v2-preload.js"), "utf8");
const grossProfitPdf = fs.readFileSync(path.join(root, "gross-profit-pdf.js"), "utf8");

assert.match(preload, /totalCalculatedHours = d\.calculatedHours \+ d\.plannedRegieHours/);
assert.match(preload, /sourcePlannedHours > 0/);
assert.match(preload, /\? number\(row\.plannedHours\) : 0/);
assert.match(hub, /fixedMaterialEk=material\*\.6,totalMaterialEk=fixedMaterialEk\+regieMaterialEk/);
assert.match(hub, /fixedMaterialProfit=material\*\.4/);
assert.match(calculationUi, /fixedMaterialProfit=d\.material\*\.4/);
assert.match(calculationUi, /fix 40 %/);
assert.match(hub, /documentPerHour=actual>0\?documentNet\/actual:0/);
assert.match(hub, /gespeicherte \+ ausgestellte Rechnungen netto/);
assert.match(cockpit, /documents\.filter\(x=>x\?\.type==="regie_report"\)/);
assert.match(cockpit, /liveInvoiceNet=billedNet\+draftNet/);
assert.match(cockpit, /hasIssuedClosingInvoice=issuedInvoices\.some/);
assert.match(cockpit, /emailCount\+\(emailCount===1\?" E-Mail":" E-Mails"\)/);
assert.match(cockpit, /wwAdditionalHours=Math\.max\(0,actual-peopleHours\)/);
assert.match(cockpit, /WinWorker – zusätzlich/);
assert.match(cockpit, /Sollstunden gesamt/);
assert.match(cockpit, /Grundkalkulation \+ \$\{hours\(plannedRegie\)\} Regie\/Nachtrag/);
assert.match(cockpit, /Offene Regieberichte/);
assert.match(cockpit, /value\.textContent=money\(regieBilling\.openAmount\)/);
assert.match(cockpit, /Stunden \+ Material laut Rapport/);
assert.doesNotMatch(liveHours, /pulseItem\("Offene Regieberichte"\)/);
assert.match(hub, /regieReportHours=String\(reportRegie\)/);
assert.match(liveHours, /function fusedPeople\(jobId\)/);
assert.match(liveHours, /function patchHoursTab\(id\)/);
assert.match(liveHours, /patchHoursTab\(id\)/);
assert.match(hub, /<div class="bk-label">Rohertrag<\/div>/);
assert.match(hub, /grossProfit=documentNet-laborCosts\.total-totalMaterialEk/);
assert.match(hub, /calculation\?\.fullCostRate/);
assert.match(hub, /Berechnung anzeigen/);
assert.match(hub, /data-bk-gross-profit-details/);
assert.match(hub, /calculation\.salaryCostRate/);
assert.match(hub, /wageCost=hours\*wageRate/);
assert.match(hub, /gkCost=hours\*gkRate/);
assert.match(hub, /Stunden × Lohnkostensatz \+ Stunden × GK-Satz = Gesamtkosten/);
assert.match(hub, /Monatsbrutto × 18 ÷ 1\.650/);
assert.match(hub, /jährliche Gemeinkosten ÷ produktive Jahresstunden/);
assert.match(hub, /Lohnkosten<\/th><th class="num">GK €\/h<\/th><th class="num">GK-Kosten<\/th><th class="num">Gesamtkosten/);
assert.match(hub, /cost\.wageTotal/);
assert.match(hub, /cost\.gkTotal/);
assert.match(liveHours, /grossProfit=documentNet-wage\.total-materialEk/);
assert.match(liveHours, /profitDetailsHtml/);
assert.match(hub, /data-bk-gross-profit-pdf/);
assert.match(hub, /economy\/gross-profit\.pdf/);
assert.match(liveHours, /_bkGrossProfitPdfData/);
assert.match(server, /createGrossProfitPdf/);
assert.match(server, /economy\/gross-profit\.pdf/);
assert.match(grossProfitPdf, /Rohertragsberechnung/);
assert.match(grossProfitPdf, /Summen Mitarbeiter/);
assert.match(grossProfitPdf, /GK-Kosten/);
assert.doesNotMatch(hub, /Produktive WW-Stempelstunden/);
assert.match(calculationGrid, /const totalTarget = target \+ plannedRegie/);
assert.match(calculationGrid, /set\("kcv2SumHours", hours\(totalTarget\)\)/);
assert.match(chronik, /function collectSurface\(regies,documents=\[\],metaRows=\[\]\)/);
assert.match(chronik, /function collectSurfacePeople\(regies,documents=\[\]\)/);
assert.match(chronik, /\/documentation`\)\.catch\(\(\)=>\(\{items:\[\]\}\)\)/);
assert.match(chronik, /data-bz-relevant/);
assert.match(chronik, /data-bz-save/);
assert.match(chronik, /data-bz-add-material/);
assert.match(chronik, /data-bz-create-material/);
assert.match(chronik, /custom:true,name/);
assert.match(chronik, /surface\.filter\(x=>x\.relevant\)/);
assert.match(chronik, /surface\.filter\(x=>!x\.relevant\)/);
assert.match(chronik, /<h4>Oberflächenrelevant<\/h4>/);
assert.match(chronik, /<h4>Material<\/h4>/);
assert.doesNotMatch(hub, /data-bk-tab="material"/);
assert.doesNotMatch(hub, /data-bk-panel="material"/);
assert.match(server, /custom: !!row\?\.custom/);
assert.match(server, /name: String\(row\?\.name/);
assert.match(server, /surfaceMaterialMeta: cleanSurfaceMaterialMeta/);

console.log("baustellen economy value tests passed");
