"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),root=path.join(__dirname,"..");
const access=fs.readFileSync(path.join(root,"customer-portal-access.js"),"utf8"),ui=fs.readFileSync(path.join(root,"public/ui/kundenportal.js"),"utf8"),html=fs.readFileSync(path.join(root,"public/kundenportal.html"),"utf8"),pkg=require(path.join(root,"package.json"));
const terms=fs.readFileSync(path.join(root,"offer-terms.js"),"utf8"),pdf=fs.readFileSync(path.join(root,"offer-html-pdf.js"),"utf8"),server=fs.readFileSync(path.join(root,"server.js"),"utf8");
assert.equal(pkg.dependencies.qrcode,"^1.5.4","QR-Code wird lokal und ohne Fremddienst erzeugt");
for(const text of ['purpose==="offer"','90*86400000','QRCode.toString','offerNumber','offerRevision','customerOffer(ctx)','/kundenportal/api/offer/accept','req.body?.confirmed!==true','status:"Auftrag"','offer_customer_accepted'])assert.ok(access.includes(text),`Sicherer Angebotsauftrag enthält ${text}`);
for(const text of ['offer:"Angebot"','Angebot verbindlich beauftragen','offerConfirm','offer/accept','window.confirm'])assert.ok(ui.includes(text),`Kundenportal zeigt und bestätigt das Angebot: ${text}`);
assert.ok(html.includes("20260918-offer-original-agb-2"),"Kundenportal lädt Original-PDF und vollständige AGB ohne Alt-Cache");
for(const text of ["Muster-Widerrufsformular","vierzehn Tagen","zuzüglich allfälliger beauftragter Nachträge","Feldkircherstraße 45","FN 15539b","FN 77707a"])assert.ok(terms.includes(text),`Rechtliche Angebotsanlage enthält ${text}`);
assert.ok(pdf.includes("appendOfferLegalAnnex"),"AGB und Rücktrittsunterlagen werden an die verbindliche PDF angehängt");
assert.ok(server.includes("offer-approved-original")&&server.includes("appendOfferLegalAnnex(originalPdf)"),"Freigegebene Originalseiten bleiben Grundlage der Kunden-PDF");
assert.ok(server.includes('"x-approved-pdf-correction"')&&server.includes("offer_pdf_corrected_after_acceptance")&&server.includes("customerAcceptanceUnchanged:accepted"),"Eine freigegebene PDF kann nach Annahme nur protokolliert korrigiert werden; der Auftrag bleibt unverändert");
assert.ok(access.includes('new Set(["offer-approved-original","offer-approved-correction"])'),"Das Kundenportal akzeptiert keine automatisch nachgebaute PDF als verbindliches Angebot");
console.log("OK: Kundenportal-QR und verbindliche Angebotsbeauftragung sind verdrahtet.");
