'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require(process.env.PGLITE_MODULE_PATH||'@electric-sql/pglite');const {prepareTasks,importTasks}=require('../storage/import-tasks');
test('task import preserves exact sources, assignments, local appointments and unresolved IDs without name guesses',async()=>{const db=new PGlite(),pool={connect:async()=>({query:(s,a)=>db.query(s,a),release(){}})};try{
 for(const f of ['002-domain-core.sql','003-business-domain.sql','004-people-communications.sql','008-task-import.sql'])await db.exec(fs.readFileSync(__dirname+'/../migrations/'+f,'utf8'));
 const companyId=(await db.query("INSERT INTO kristine.companies(name) VALUES('A') RETURNING id")).rows[0].id;const other=(await db.query("INSERT INTO kristine.companies(name) VALUES('B') RETURNING id")).rows[0].id;const sourceInstanceId=(await db.query("INSERT INTO kristine.source_instances(company_id,system_code,instance_key) VALUES($1,'kristine','test') RETURNING id",[companyId])).rows[0].id;
 const party=(await db.query("INSERT INTO kristine.parties(company_id,kind,display_name) VALUES($1,'person','A') RETURNING id",[companyId])).rows[0].id;const employee=(await db.query("INSERT INTO kristine.employees(company_id,party_id,display_name) VALUES($1,$2,'A') RETURNING id",[companyId,party])).rows[0].id;const sid=(await db.query("INSERT INTO kristine.source_records(company_id,source_instance_id,entity_type,external_id) VALUES($1,$2,'employee','E') RETURNING id",[companyId,sourceInstanceId])).rows[0].id;await db.query('INSERT INTO kristine.external_references(company_id,source_record_id,employee_id) VALUES($1,$2,$3)',[companyId,sid,employee]);
 const base={id:'T',title:'Test',taskType:'Termin',priority:'heute',status:'done',createdAt:'2026-10-06T12:00:00Z',completedAt:'2026-10-06T13:00:00Z',dueDate:'2026-10-06',assigneeId:'E',creatorId:'system',jobId:'missing',reminder:'Original note',appointment:{date:'2026-10-07',from:'08:00',to:'09:00',calendarOwner:'office',calendarAccount:'primary'},visitProtocol:{discussion:'exact text'}};const rows=[base,{...base,id:'U',assigneeId:'unknown',createdAt:'2026-10-06T12:00:00',appointment:null}];const originalText='[\n'+rows.map(x=>JSON.stringify(x)).join(',\n')+'\n]';const run=t=>importTasks(pool,{companyId,sourceInstanceId,originalText:t});const result=await run(originalText);assert.deepEqual(result,{created:2,unchanged:0,assignments:1,appointments:1,review:2,verified:2});assert.deepEqual(await run(originalText),{created:0,unchanged:2,assignments:0,appointments:0,review:2,verified:2});assert.equal((await db.query("SELECT original_text FROM kristine.source_record_versions v JOIN kristine.source_records s ON s.id=v.source_record_id WHERE s.entity_type='task_file'")).rows[0].original_text,originalText);
 const before=(await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n;await assert.rejects(run(originalText.replace('Original note','Changed')),/changed/);await assert.rejects(importTasks(pool,{companyId:other,sourceInstanceId,originalText}),/mismatch/);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n,before);await db.query("UPDATE kristine.tasks SET status='open'");await assert.rejects(run(originalText),/verification/);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n,before);
 assert.equal(prepareTasks(JSON.stringify([{...base,taskType:'Freigabe'}]))[0].task_type,'approval');assert.throws(()=>prepareTasks(JSON.stringify([base,base])),/duplicate/);assert.throws(()=>prepareTasks(JSON.stringify([{...base,dueDate:'2026-02-30'}])),/date/);assert.throws(()=>prepareTasks(JSON.stringify([{...base,priority:'guess'}])),/state/);
 }finally{await db.close();}});
