'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require(process.env.PGLITE_MODULE_PATH||'@electric-sql/pglite');const {importDayHistory,prepareDayHistory}=require('../storage/import-day-history');
test('day source import preserves status distinctions, full ordered histories and unresolved identities without activating payroll',async()=>{const db=new PGlite(),pool={connect:async()=>({query:(s,a)=>db.query(s,a),release(){}})};try{
 for(const f of ['002-domain-core.sql','011-day-history-import.sql'])await db.exec(fs.readFileSync(__dirname+'/../migrations/'+f,'utf8'));
 const companyId=(await db.query("INSERT INTO kristine.companies(name) VALUES('A') RETURNING id")).rows[0].id,sourceInstanceId=(await db.query("INSERT INTO kristine.source_instances(company_id,system_code,instance_key) VALUES($1,'kristine','test') RETURNING id",[companyId])).rows[0].id;
 const history=[{at:'local time',by:'Office',before:[{from:'07:00',to:''}],after:[{from:'07:00',to:'17:00'}]},{at:'later',by:'Office',reason:'confirmed',before:[{from:'07:00',to:'17:00'}],after:[{from:'07:00',to:'17:06'}]}];const base={employeeId:'former',date:'2026-07-29',employeeName:'E',createdAt:'2026-07-29 17:06'};const files=[{name:'day-closes.json',originalText:JSON.stringify([{...base,id:'close',complete:false,confirmed:false,status:'pending',checks:{materials:false}}])},{name:'day-releases.json',originalText:JSON.stringify([{...base,id:'release',released:true,returned:true,returnedReason:'retained'}])},{name:'day-corrections.json',originalText:JSON.stringify([{...base,id:'correction',originalSegments:history[0].before,history}])},{name:'day-review-entries.json',originalText:JSON.stringify([{...base,id:'review',jobId:'missing',content:{text:'original'},history:[{at:'now',action:'move',oldJobId:'A',newJobId:'B'}]}])}];const run=files=>importDayHistory(pool,{companyId,sourceInstanceId,files});const a=await run(files);assert.equal(a.verified,4);assert.equal(a.historyVerified,3);assert.equal(a.withReview,4);const b=await run(files);assert.equal(b.created,0);assert.equal(b.unchanged,4);const close=(await db.query("SELECT status_flags,created_at_original FROM kristine.imported_day_records WHERE record_kind='close'")).rows[0];assert.deepEqual(close.status_flags,{complete:false,confirmed:false});assert.equal(close.created_at_original,base.createdAt);const release=(await db.query("SELECT status_flags FROM kristine.imported_day_records WHERE record_kind='release'")).rows[0];assert.deepEqual(release.status_flags,{released:true,returned:true});const h=(await db.query("SELECT h.raw_payload FROM kristine.imported_day_record_history h JOIN kristine.imported_day_records d ON d.id=h.day_record_id WHERE d.record_kind='correction' ORDER BY h.position")).rows;assert.deepEqual(h.map(x=>x.raw_payload),history);
 for(const t of ['day_closes','time_month_locks','payroll_month_closes','time_events','time_segments'])assert.equal((await db.query('SELECT count(*)::int n FROM kristine.'+t)).rows[0].n,0);
 await assert.rejects(db.query('DELETE FROM kristine.imported_day_records'),/append-only/);await assert.rejects(db.query('UPDATE kristine.imported_day_record_history SET position=20'),/append-only/);const n=(await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n;await assert.rejects(run([{...files[0],originalText:files[0].originalText.replace('pending','complete')}]),/changed/);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n,n);await assert.rejects(importDayHistory(pool,{companyId:'00000000-0000-0000-0000-000000000001',sourceInstanceId,files}),/mismatch/);assert.throws(()=>prepareDayHistory([{name:'unknown.json',originalText:'[]'}]),/Unknown/);assert.throws(()=>prepareDayHistory([files[0],files[0]]),/duplicate/);
 }finally{await db.close();}});
