'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require(process.env.PGLITE_MODULE_PATH||'@electric-sql/pglite');const {prepareTimeSources,importTimeSources}=require('../storage/import-time-sources');
test('time sources preserve duplicates and local times while archive overlap never creates live payroll segments',async()=>{const db=new PGlite(),pool={connect:async()=>({query:(s,a)=>db.query(s,a),release(){}})};try{
 for(const f of ['002-domain-core.sql','003-business-domain.sql','004-people-communications.sql','006-address-source-mapping.sql','007-contact-groups.sql','009-time-source-import.sql'])await db.exec(fs.readFileSync(__dirname+'/../migrations/'+f,'utf8'));
 const companyId=(await db.query("INSERT INTO kristine.companies(name) VALUES('A') RETURNING id")).rows[0].id,other=(await db.query("INSERT INTO kristine.companies(name) VALUES('B') RETURNING id")).rows[0].id,sourceInstanceId=(await db.query("INSERT INTO kristine.source_instances(company_id,system_code,instance_key) VALUES($1,'kristine','test') RETURNING id",[companyId])).rows[0].id;
 const eid=(await db.query("INSERT INTO kristine.employees(company_id,display_name) VALUES($1,'Employee') RETURNING id",[companyId])).rows[0].id,sid=(await db.query("INSERT INTO kristine.source_records(company_id,source_instance_id,entity_type,external_id) VALUES($1,$2,'employee','E') RETURNING id",[companyId,sourceInstanceId])).rows[0].id;await db.query('INSERT INTO kristine.external_references(company_id,source_record_id,employee_id) VALUES($1,$2,$3)',[companyId,sid,eid]);
 const event={employeeId:'E',date:'2026-10-06',type:'start',at:'07:00',actualAt:'07:12',jobId:'missing',adjusted:true};const day={id:'D',employeeId:'E',date:'2026-10-06',source:'day_release',releasedAt:'original',segments:[{id:'same',type:'work',from:'07:00',to:'12:00',jobId:'missing'},{id:'same',type:'pause',from:'12:00',to:'12:30'},{id:'open',type:'work',from:'17:06',to:''}]};const input={eventsText:'[\n'+JSON.stringify(event)+',\n'+JSON.stringify(event)+'\n]',archiveText:JSON.stringify([day]),supplementary:[{name:'day-corrections.json',originalText:'[ {"history":[]} ]'}]};const run=x=>importTimeSources(pool,{companyId,sourceInstanceId,...x});const first=await run(input);assert.equal(first.eventsCreated,2);assert.equal(first.archiveDaysCreated,1);assert.equal(first.archiveSegmentsVerified,3);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.time_segments')).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.payroll_month_closes')).rows[0].n,0);const times=(await db.query('SELECT booked_time,actual_local_time,actual_at FROM kristine.time_events')).rows;assert.deepEqual(times[0],{booked_time:'07:00:00',actual_local_time:'07:12:00',actual_at:null});const open=(await db.query('SELECT ends_local,import_review_reasons FROM kristine.project_time_archive_segments WHERE position=2')).rows[0];assert.equal(open.ends_local,null);assert.ok(open.import_review_reasons.includes('end_time_missing'));const replay=await run(input);assert.equal(replay.eventsCreated,0);assert.equal(replay.eventsUnchanged,2);assert.equal(replay.archiveDaysUnchanged,1);assert.equal((await db.query("SELECT original_text FROM kristine.source_records s JOIN kristine.source_record_versions v ON v.source_record_id=s.id WHERE s.external_id='time-events.json'")).rows[0].original_text,input.eventsText);
 const before=(await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n;await assert.rejects(run({...input,eventsText:input.eventsText.replace('07:12','07:13')}),/changed/);await assert.rejects(run({...input,eventsText:JSON.stringify([{...event,employeeId:'unknown'}])}),/employee/);await assert.rejects(importTimeSources(pool,{...input,companyId:other,sourceInstanceId}),/mismatch/);await assert.rejects(run({...input,supplementary:[{name:'credentials.json',originalText:'[]'}]}),/supplementary/);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n,before);
 await db.query("UPDATE kristine.project_time_archive_segments SET reason='changed' WHERE position=0");await assert.rejects(run(input),/verification/);assert.equal((await db.query('SELECT count(*)::int n FROM kristine.import_runs')).rows[0].n,before);
 assert.throws(()=>prepareTimeSources({...input,archiveText:JSON.stringify([day,day])}),/duplicate/);assert.throws(()=>prepareTimeSources({...input,eventsText:JSON.stringify([{...event,at:'25:00'}])}),/time/);
 }finally{await db.close();}});
