const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const script=fs.readFileSync(path.join(__dirname,'../public/ui/baustellen-chronik.js'),'utf8');
const functions=script.slice(script.indexOf('  function surfaceCategory('),script.indexOf('  function collectSurfacePeople('));
const context={num:v=>Number(v)||0,dayKey:(...values)=>values.find(Boolean)?.slice(0,10)||''};vm.createContext(context);vm.runInContext(functions,context);
const bookings=[{source:'innovatint-history',product:'Intelligent Matt Emulsion',colourTone:'NCS S 3060-Y20R',liters:2.5,component:'gang und schlafzimmer',baseName:'Yellow',size:'2,5 L'}, {source:'innovatint-history',product:'Intelligent Satin',colourTone:'NCS S 2020-Y20R',liters:1}, {source:'manual',product:'Abdeckband',quantity:1}, {source:'manual',brand:'Little Greene',product:'Absolute Matt',liters:5}];
let rows=context.collectSurface([],[],[],bookings);
assert.equal(rows.filter(x=>x.relevant).length,3);
const matt=rows.find(x=>x.name.startsWith('Intelligent Matt'));
assert.equal(matt.category,'Beschichtung');assert.equal(matt.quantity,2.5);assert.equal(matt.use,'gang und schlafzimmer');
assert.equal(rows.find(x=>x.name==='Abdeckband').relevant,false);
rows=context.collectSurface([],[],[{key:matt.key,relevant:false,note:'Bestehende Notiz',use:'Wohnzimmer'}],bookings);
assert.equal(rows.find(x=>x.key===matt.key).relevant,true);assert.equal(rows.find(x=>x.key===matt.key).note,'Bestehende Notiz');
assert.equal(context.collectSurface([],[],[],[{source:'innovatint-history',product:'Intelligent Primer',quantity:1}])[0].category,'Grundierung');
console.log('OK: Little Greene is surface relevant for existing and new mixing assignments, preserving quantities and notes; other materials remain unchanged.');
