'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{launchTestBrowser}=require('./browser-runtime');
(async()=>{const browser=await launchTestBrowser({headless:true});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let acknowledged=false,confirmed=false;
 const rows=[{file:'message:text',category:'text',content:'Zimmer vier: Wände in <hammrock> pale 351',employeeName:'Alex Krista',date:'2026-10-06',groupId:'alex',status:'pending'},{file:'unknown/note.ogg',url:'/audio.ogg',category:'audio',content:'Meine gesprochene Notiz',employeeName:'Alex Krista',date:'2026-10-06',groupId:'alex',status:'pending'}];
 await page.route('http://messages.test/**',route=>{const u=new URL(route.request().url());if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:'<main class="shell"><div class="hero"></div></main><script src="/photos.js"></script>'});if(u.pathname==='/photos.js')return route.fulfill({contentType:'text/javascript; charset=utf-8',body:fs.readFileSync(path.join(__dirname,'../public/ui/photo-inbox.js'),'utf8')});if(u.pathname==='/admin/api/jobs')return route.fulfill({json:{jobs:[{jobId:'26108',name:'Wiederin'}]}});if(u.pathname.endsWith('/acknowledge')){assert.deepEqual(route.request().postDataJSON().files,['message:text']);acknowledged=true;rows[0].status='acknowledged';return route.fulfill({json:{ok:true}})}if(u.pathname.endsWith('/confirm')){assert.deepEqual(route.request().postDataJSON().changes,[{file:'unknown/note.ogg',jobId:'26108'}]);confirmed=true;rows[1].status='confirmed';rows[1].jobId='26108';return route.fulfill({json:{ok:true}})}if(u.pathname==='/kristine/api/photo-inbox')return route.fulfill({json:{items:rows.filter(x=>u.searchParams.get('processed')==='true'?x.status!=='pending':x.status==='pending')}});return route.fulfill({body:''})});
 await page.goto('http://messages.test/');await page.locator('[data-file]').first().waitFor();assert.equal(await page.locator('audio').count(),1);assert.equal(await page.locator('hammrock').count(),0);await page.getByText('Zimmer vier: Wände in <hammrock> pale 351',{exact:true}).waitFor();
 await page.locator('[data-search]').fill('Zimmer vier');assert.equal(await page.locator('[data-file]').count(),1);await page.locator('[data-read]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-file]').length===0);assert(acknowledged);
 await page.locator('[data-search]').fill('');await page.locator('[data-job]').fill('26108');await page.locator('[data-confirm]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-file]').length===0);assert(confirmed);
 await page.locator('[data-processed]').check();await page.waitForFunction(()=>document.querySelectorAll('[data-file]').length===2);assert.equal(await page.locator('[data-confirm]:visible').count(),1);assert((await page.locator('[data-groups]').innerText()).includes('Gelesen · ohne Baustelle abgelegt')); await page.getByText('Zugeordnet · 26108',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('OK: voice/text previews, search, read without job, confirmation and processed history');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
