"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),root=path.resolve(__dirname,"..");
const hub=fs.readFileSync(path.join(root,"public","ui","baustellen-knowledge-hub.js"),"utf8"),outgoing=fs.readFileSync(path.join(root,"brain_outgoing_invoices.py"),"utf8");
assert.match(hub,/addImportedMaterials/);
assert.match(hub,/regieHours=.*laborTotal=.*materialTotal=/);
assert.match(outgoing,/Regiedaten übernehmen/);
assert.match(outgoing,/Regiearbeit lt\. Berichten/);
assert.match(outgoing,/Material lt\. Berichten/);
assert.match(outgoing,/discountPercent:20/);
for(const label of ["TR erstellen","Schlussrechnung","Extra-Rechnung"])assert.ok(outgoing.includes(label));
assert.match(outgoing,/startInvoiceKind\('SR'\)/);
assert.match(outgoing,/startInvoiceKind\('RE'\)/);
console.log("regie invoice link test: ok");
