"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),root=path.resolve(__dirname,"..");
const hub=fs.readFileSync(path.join(root,"public","ui","baustellen-knowledge-hub.js"),"utf8"),outgoing=fs.readFileSync(path.join(root,"brain_outgoing_invoices.py"),"utf8"),tower=fs.readFileSync(path.join(root,"public","kontrollzentrum.html"),"utf8");
assert.match(hub,/addImportedMaterials/);
assert.match(hub,/regieHours=.*laborTotal=.*materialTotal=/);
assert.match(outgoing,/Regiedaten übernehmen/);
assert.match(outgoing,/Regiearbeit lt\. Berichten/);
assert.match(outgoing,/Material lt\. Berichten/);
assert.match(outgoing,/discountPercent:20/);
for(const label of ["1. TR","Schlussrechnung","Extra-Rechnung"])assert.ok(outgoing.includes(label));
assert.match(outgoing,/\['SR','SR'\]/);
assert.match(outgoing,/\['RE','Rechnung'\]/);
assert.match(outgoing,/body\.label=body\.label\|\|designation/);
assert.match(outgoing,/const isExtra=kind==='RE'/);
assert.match(outgoing,/Nächste freie Rechnungsnummer/);
assert.match(outgoing,/\/api\/outgoing\/next-number/);
assert.match(outgoing,/loadNextNumber\(\)/);
assert.match(outgoing,/\+ Neue Rechnung/);
assert.match(outgoing,/Verkauf ohne Projekt/);
assert.match(outgoing,/period-summary/);
assert.match(outgoing,/WinWorker und KRISTINE/);
assert.match(tower,/Umsatz 2026 aus WW \+ KRISTINE/);
assert.match(tower,/davon KRISTINE/);
console.log("regie invoice link test: ok");
