"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/ui/kristine-task-list.js"),"utf8");
const topbar=fs.readFileSync(path.join(__dirname,"../public/ui/topbar.js"),"utf8");
const start=source.indexOf("  function taskGroupKey(task)"),end=source.indexOf("  function install()",start);
assert(start>=0&&end>start,"taskGroupKey fehlt");
const context=vm.createContext({});vm.runInContext(source.slice(start,end)+"\nglobalThis.taskGroupKey=taskGroupKey;globalThis.taskFileInfo=taskFileInfo;",context);
assert.equal(context.taskGroupKey({title:"Kundenpunkt prüfen · Kunde"}),"customer");
assert.equal(context.taskGroupKey({title:"Irgendwas",reminder:"[FINANCE_APPROVAL]id=1"}),"invoice");
assert.equal(context.taskGroupKey({title:"Regiebericht prüfen · Rapport 4"}),"regie");
assert.equal(context.taskGroupKey({title:"Rückruf Kunde"}),"other");
assert.equal(context.taskFileInfo({jobId:"26025",jobName:"Vonblon, Artur"}).key,"job:26025");
assert.equal(context.taskFileInfo({jobId:"26025",jobName:"Vonblon, Artur"}).label,"Vonblon, Artur");
assert.equal(context.taskFileInfo({jobName:"Egon Allgäuer"}).key,"name:egon allgäuer");
assert.equal(context.taskFileInfo({}).label,"Ohne zugeordnete Akte");
for(const label of ["Aufgaben","Regie","Rechnungen","Kundenpunkte"])assert(source.includes(`label:\"${label}\"`));
assert(source.indexOf('label:"Aufgaben"')<source.indexOf('label:"Regie"'));
assert(source.indexOf('label:"Regie"')<source.indexOf('label:"Rechnungen"'));
assert(source.indexOf('label:"Rechnungen"')<source.indexOf('label:"Kundenpunkte"'));
assert(source.includes('class="krista-task-group"'));
assert(source.includes('class="krista-task-file-bar"'));
assert(source.includes('${count} ${count === 1 ? "Aufgabe" : "Aufgaben"}'));
assert(source.includes('group.key === "customer" ? taskFileGroupsHtml'));
assert(source.includes("window.openKristaTaskEditor = openTaskEditor"));
assert(source.includes('appointmentRequest("PATCH"'));
assert(source.includes("window.persistTasks()"));
assert(topbar.includes("kristine-task-list.js?v=20260918-file-groups"));
console.log("OK: Aufgaben werden in vier einklappbare Bereiche gegliedert.");
