# coding: utf-8
CSS=r''':root{color-scheme:dark;--bg:#101316;--card:#171b20;--line:#343c46;--text:#eef2f4;--muted:#9da8b3;--accent:#438b5c;--warn:#e3b55a;--danger:#e47f7f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.shell{max-width:1500px;margin:auto;padding:18px}.head,.section-title,.footer{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.head h1{margin:0}.sub,.hint{color:var(--muted);font-size:12px}.back,.pdf{color:inherit;font-weight:800}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:16px 0}.metric,.card,.note{border:1px solid var(--line);border-radius:13px;background:var(--card);padding:12px}.metric span{display:block;color:var(--muted);font-size:12px}.metric strong{font-size:20px}.card{margin-bottom:14px}.row{display:grid;grid-template-columns:34px 105px minmax(180px,1.4fr) minmax(120px,.8fr) 125px 155px 100px;gap:9px;align-items:center;padding:10px 6px;border-top:1px solid var(--line);font-size:13px}.row:first-child{border-top:0}.submitted-row{grid-template-columns:105px minmax(180px,1.4fr) minmax(120px,.8fr) 125px 165px 100px}.archive-row{grid-template-columns:145px minmax(220px,1.5fr) minmax(260px,2fr) 125px 145px}.amount{font-weight:850;text-align:right}.gross{color:var(--muted);font-size:11px;text-decoration:line-through}.status{font-size:11px;font-weight:850}.status.sepa_submitted{color:#9cc7ff}.status.paid,.status.approved{color:#82d49d}.status.pending{color:var(--warn)}.status.blocked{color:var(--danger)}.status.reduced{color:#9cc7ff}select,button{background:#252c34;color:inherit;border:1px solid #485461;border-radius:9px;padding:8px 10px}.sepa-download{padding:6px 8px;font-size:11px;cursor:pointer}.footer{position:sticky;bottom:0;background:#17231c;border:1px solid #496451;border-radius:13px;padding:12px}.footer button{background:var(--accent);font-weight:850}.empty{padding:20px;text-align:center;color:var(--muted)}.unknown .row{grid-template-columns:105px minmax(180px,1.4fr) minmax(120px,.8fr) 115px 190px}.note{margin-bottom:14px;color:var(--muted)}.approval-note{background:#171f18;border-color:#425747}.approval-note.warn{background:#241d12;border-color:#66512e}.approval-note strong{color:var(--text)}details.card>summary{cursor:pointer;font-size:18px;font-weight:800;padding:4px 0}details.card[open]>summary{margin-bottom:10px}@media(max-width:1050px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.metrics{grid-template-columns:1fr 1fr}.row,.unknown .row,.submitted-row,.archive-row{grid-template-columns:1fr 1fr}.amount{text-align:left}.footer{position:static}}@media(max-width:520px){.metrics,.row,.unknown .row,.submitted-row,.archive-row{grid-template-columns:1fr}}'''

CSS += ".submitted-row{grid-template-columns:105px minmax(180px,1.4fr) minmax(120px,.8fr) 125px 165px 130px 70px}"
CSS += r'''.row{grid-template-columns:34px 105px minmax(180px,1.4fr) minmax(120px,.8fr) 125px 190px 100px}.sepa-download{background:var(--accent)!important;border-color:#67a17a!important;color:#fff!important;font-weight:900!important}'''

def payments_page():
 return r'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KRISTINE · Bezahlung</title><style>__CSS__</style></head><body><main class="shell">
<div class="head"><div><h1>Bezahlung</h1><div class="sub">Bezahl-OP · nur freigegebene Überweisungen dürfen in SEPA.</div></div><a class="back" href="/">← The Brain</a></div>
<div class="metrics"><div class="metric"><span>Bezahl-OP</span><strong id="cnt">–</strong></div><div class="metric"><span>OP zahlbar</span><strong id="tot">–</strong></div><div class="metric"><span>Freigaben</span><strong id="approvals">–</strong></div><div class="metric"><span>Ausgewählt</span><strong id="sel">0</strong></div><div class="metric"><span>Zahlungssumme</span><strong id="sum">0,00 €</strong></div></div>
<div id="approvalInfo" class="note approval-note">Freigaben aus KRISTINE werden geprüft …</div>
<section class="card"><div class="section-title"><h2>Offene Überweisungen</h2><span class="hint">Nur freigegebene Rechnungen sind auswählbar. Kürzungen werden als tatsächlicher Überweisungsbetrag verwendet.</span></div><div id="rows"><div class="empty">Wird geladen …</div></div></section>
<section class="card" id="sepaSubmittedCard"><div class="section-title"><h2>An SEPA übergeben</h2><span class="hint">Bleibt sichtbar, bis der CAMT-Abgleich die Zahlung bestätigt.</span></div><div id="submitted"><div class="empty">Wird geladen …</div></div></section>
<details class="card" id="sepaArchiveCard"><summary>SEPA-Archiv</summary><div class="hint">Die ursprüngliche XML-Datei kann hier jederzeit unverändert erneut geladen werden.</div><div id="sepaArchive"><div class="empty">Wird geladen …</div></div></details>
<section class="card unknown"><div class="section-title"><h2>Zahlungsart noch klären</h2><span class="hint">Einzug/Revolut/Bar verschwinden danach aus dem Bezahl-OP.</span></div><div id="unknown"><div class="empty">Wird geladen …</div></div></section>
<div class="footer"><div><span id="fc">0</span> Rechnung(en) · <strong id="fs">0,00 €</strong></div><button id="go" disabled>Zahlung vorbereiten</button></div></main><script>
(()=>{
 const box=document.getElementById('rows'),ub=document.getElementById('unknown'),sb=document.getElementById('submitted'),ab=document.getElementById('sepaArchive'),go=document.getElementById('go'),approvalInfo=document.getElementById('approvalInfo');let rows=[];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=(n,c='EUR')=>new Intl.NumberFormat('de-AT',{style:'currency',currency:c||'EUR'}).format(Number(n||0));
 const date=s=>{const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[3]+'.'+m[2]+'.'+m[1]:(s||'–')};
 const dateTime=s=>{if(!s)return '–';const d=new Date(s);return Number.isNaN(d.getTime())?date(s):new Intl.DateTimeFormat('de-AT',{dateStyle:'short',timeStyle:'short'}).format(d)};
 const opts=v=>[['unknown','– auswählen –'],['transfer','Überweisung / SEPA'],['direct_debit','Einzug / Lastschrift'],['revolut','Revolut / Kreditkarte'],['cash','Bar / Kassa']].map(([k,t])=>`<option value="${k}" ${k===v?'selected':''}>${t}</option>`).join('');
 const pdf=r=>r.path?`<a class="pdf" href="/pdf?path=${encodeURIComponent(r.path)}" target="_blank">PDF</a>`:'–';
 const batchSummary=x=>(x.items||[]).map(i=>`${i.supplier||'Empfänger'} ${money(i.amount,i.currency)}`).join(' · ')||x.summary||'–';
 const approvalLabel=r=>{if(r.approvalStatus==='approved')return '<span class="status approved">✓ freigegeben</span>';if(r.approvalStatus==='reduced')return `<span class="status reduced">✂ gekürzt · ${esc(money(r.approvalDeduction,r.currency))}</span>${r.approvalReason?`<div class="sub">${esc(r.approvalReason)}</div>`:''}`;if(r.approvalStatus==='blocked')return `<span class="status blocked">⛔ gesperrt</span>${r.approvalReason?`<div class="sub">${esc(r.approvalReason)}</div>`:''}`;if(r.approvalStatus==='pending')return '<span class="status pending">⏳ Freigabe offen</span>';return '<span class="status">Altbestand</span>'};
 const payable=r=>['approved','reduced','not_required'].includes(r.approvalStatus)&&Number(r.paymentAmount??r.amount)>0;
 function download(d){const blob=new Blob([d.xml],{type:'application/xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=d.filename||'SEPA.xml';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
 async function xml(url,items){const q=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})}),d=await q.json();if(!q.ok||!d.ok)throw Error(d.error||'SEPA-Datei konnte nicht erstellt werden');download(d);return d}
 async function archivedXml(id){const q=await fetch('/incoming/payment-batches/xml?id='+encodeURIComponent(id),{cache:'no-store'}),d=await q.json();if(!q.ok||!d.ok)throw Error(d.error||'Archivdatei konnte nicht geladen werden');download(d)}
 function selected(){const a=[...box.querySelectorAll('[data-s]:checked')].map(e=>{const [s,id]=e.dataset.s.split('|');return rows.find(r=>r.source===s&&r.id===id)}).filter(Boolean),t=a.reduce((x,r)=>x+Number(r.paymentAmount??r.amount??0),0);sel.textContent=fc.textContent=a.length;sum.textContent=fs.textContent=money(t);go.disabled=!a.length;return a}
 function render(r,u,s,d,batches){
  rows=r;cnt.textContent=d.count;tot.textContent=money(d.total);approvals.textContent=`${Number(d.approvalPendingCount||0)} offen · ${Number(d.approvalApprovedCount||0)} frei`;
  approvalInfo.classList.toggle('warn',Boolean(d.approvalSyncError||d.approvalPendingCount||d.approvalBlockedCount));approvalInfo.innerHTML=d.approvalSyncError?`<strong>Freigabe-Sync nicht erreichbar.</strong> KRISTINE-Rechnungen bleiben aus Sicherheitsgründen für SEPA gesperrt. · ${esc(d.approvalSyncError)}`:`<strong>Freigaben aus Brain:</strong> ${Number(d.approvalPendingCount||0)} warten auf Entscheidung · ${Number(d.approvalApprovedCount||0)} freigegeben/gekürzt · ${Number(d.approvalBlockedCount||0)} gesperrt.`;
  box.innerHTML=r.length?r.map(x=>{const pay=Number(x.paymentAmount??x.amount??0),reduced=x.approvalStatus==='reduced'&&Math.abs(pay-Number(x.amount||0))>.004,disabled=!payable(x);return `<div class="row"><input type="checkbox" data-s="${esc(x.source)}|${esc(x.id)}" ${disabled?'disabled':''}><div>${esc(date(x.dueDate))}</div><div><strong>${esc(x.supplier)}</strong><div class="sub">${esc(x.paymentId||'')}</div></div><div>${esc(x.invoiceNumber||'–')}</div><div class="amount">${esc(money(pay,x.currency))}${reduced?`<div class="gross">${esc(money(x.amount,x.currency))}</div>`:''}</div><div>${approvalLabel(x)}</div><div>${pdf(x)}</div></div>`}).join(''):'<div class="empty">Keine offenen Überweisungen.</div>';
  sb.innerHTML=s.length?s.map(x=>`<div class="row submitted-row"><div>${esc(date(x.dueDate))}</div><div><strong>${esc(x.supplier)}</strong><div class="sub">${esc(x.paymentId||'')}</div></div><div>${esc(x.invoiceNumber||'–')}</div><div class="amount">${esc(money(x.paymentAmount??x.amount,x.currency))}</div><div><span class="status sepa_submitted">SEPA übergeben · wartet auf CAMT</span></div><button class="sepa-download" data-regen="${esc(x.source)}|${esc(x.id)}">XML neu erstellen</button><div>${pdf(x)}</div></div>`).join(''):'<div class="empty">Derzeit nichts an SEPA übergeben.</div>';
  ab.innerHTML=batches.length?batches.map(x=>`<div class="row archive-row"><div>${esc(dateTime(x.createdAt))}</div><div><strong>${esc(x.filename)}</strong><div class="sub">${Number(x.count||0)} Überweisung(en)</div></div><div>${esc(batchSummary(x))}</div><div class="amount">${esc(money(x.total,x.currency))}</div><button class="sepa-download" data-archive="${esc(x.id)}">XML erneut laden</button></div>`).join(''):'<div class="empty">Noch keine SEPA-Datei archiviert.</div>';
  ub.innerHTML=u.length?u.map(x=>`<div class="row"><div>${esc(date(x.dueDate))}</div><div><strong>${esc(x.supplier)}</strong><div class="sub">${x.source==='KRISTINE'?approvalLabel(x):''}</div></div><div>${esc(x.invoiceNumber||'–')}</div><div class="amount">${esc(money(x.amount,x.currency))}</div><select data-m="${esc(x.source)}|${esc(x.id)}">${opts(x.paymentMethod)}</select></div>`).join(''):'<div class="empty">Keine ungeklärten Zahlungsarten.</div>';
  box.querySelectorAll('[data-s]').forEach(e=>e.onchange=selected);sb.querySelectorAll('[data-regen]').forEach(e=>e.onclick=async()=>{if(!confirm('Für diese ältere Übergabe eine neue SEPA-XML erzeugen?\n\nNeue Übergaben werden zusätzlich als exakte Originaldatei archiviert.'))return;const [source,id]=e.dataset.regen.split('|');try{await xml('/incoming/payment-batch/xml',[{source,id}])}catch(error){alert(error.message)}});ab.querySelectorAll('[data-archive]').forEach(e=>e.onclick=()=>archivedXml(e.dataset.archive).catch(error=>alert(error.message)));ub.querySelectorAll('[data-m]').forEach(e=>e.onchange=async()=>{const [source,id]=e.dataset.m.split('|'),q=await fetch('/incoming/payment-meta',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,id,paymentMethod:e.value})}),j=await q.json();if(!q.ok||!j.ok)alert(j.error||'Fehler');else load()});selected()
 }
 async function load(){const [oq,aq]=await Promise.all([fetch('/incoming/payment-open-items',{cache:'no-store'}),fetch('/incoming/payment-batches',{cache:'no-store'})]),[d,a]=await Promise.all([oq.json(),aq.json()]);if(!oq.ok||!d.ok)throw Error(d.error||'Bezahl-OP konnte nicht geladen werden');if(!aq.ok||!a.ok)throw Error(a.error||'SEPA-Archiv konnte nicht geladen werden');render(d.items||[],d.unclassified||[],d.submitted||[],d,a.batches||[])}
 go.onclick=async()=>{const a=selected();if(!a.length||!confirm(`${a.length} freigegebene Rechnung(en) für SEPA vorbereiten?\n\nZahlungssumme: ${money(a.reduce((s,x)=>s+Number(x.paymentAmount??x.amount??0),0))}\n\nDie XML-Datei wird sofort heruntergeladen und im SEPA-Archiv gesichert. Bezahlt wird erst nach Bankfreigabe und späterem CAMT-Abgleich.`))return;try{const d=await xml('/incoming/payment-batch/prepare',a.map(x=>({source:x.source,id:x.id})));alert(`${d.count} Rechnung(en) · ${money(d.total)}\n\nSEPA-Datei heruntergeladen und im Archiv gesichert.`);load()}catch(error){alert(error.message)}};
 load().catch(e=>box.innerHTML=`<div class="empty">${esc(e.message)}</div>`)
})();
</script></body></html>'''.replace("__CSS__", CSS)

def revolut_page():
 return fr'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KRISTINE · Revolut</title><style>{CSS}</style></head><body><main class="shell"><div class="head"><div><h1>Revolut</h1><div class="sub">Eigener Abgleich für Karten-/Onlinebelege.</div></div><a class="back" href="/">← Erfassung</a></div><div class="note">Jede Revolut-Bewegung wird gegen Rechnung/Beleg abgeglichen. Offene Fälle bleiben sichtbar: Beleg fehlt, Zuordnung offen oder privat. Bank → Revolut ist nur Umbuchung.</div><div class="metrics"><div class="metric"><span>Belege</span><strong id="cnt">–</strong></div><div class="metric"><span>Offen</span><strong id="open">–</strong></div><div class="metric"><span>Offener Betrag</span><strong id="tot">–</strong></div><div class="metric"><span>Privat</span><strong>folgt</strong></div></div><section class="card"><div class="section-title"><h2>Belege / Rechnungen</h2><span class="hint">Transaktionsimport + Mail-Belegsuche folgt als nächster Schritt.</span></div><div id="rows"><div class="empty">Wird geladen …</div></div></section></main><script>
(()=>{{const b=document.getElementById('rows'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c])),money=n=>new Intl.NumberFormat('de-AT',{{style:'currency',currency:'EUR'}}).format(Number(n||0));fetch('/incoming/revolut/items',{{cache:'no-store'}}).then(r=>r.json().then(d=>[r,d])).then(([r,d])=>{{if(!r.ok||!d.ok)throw Error(d.error||'Fehler');cnt.textContent=d.count;open.textContent=d.openCount;tot.textContent=money(d.openTotal);b.innerHTML=(d.items||[]).length?(d.items||[]).map(x=>`<div class="row" style="grid-template-columns:105px minmax(180px,1.5fr) minmax(120px,.8fr) 115px 135px 100px"><div>${{esc(x.invoiceDate||'–')}}</div><div><strong>${{esc(x.supplier)}}</strong></div><div>${{esc(x.invoiceNumber||'–')}}</div><div class="amount">${{money(x.amount)}}</div><div class="status ${{esc(x.paymentStatus)}}">${{x.paymentStatus==='paid'?'bezahlt':'Abgleich offen'}}</div><div>${{x.path?`<a class="pdf" href="/pdf?path=${{encodeURIComponent(x.path)}}" target="_blank">PDF</a>`:'Beleg fehlt'}}</div></div>`).join(''):'<div class="empty">Noch keine Revolut-Belege markiert.</div>'}}).catch(e=>b.innerHTML=`<div class="empty">${{esc(e.message)}}</div>`)}})();
</script></body></html>'''
