BEGIN;
CREATE TABLE kristine.company_rule_runs (
 sequence bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,company_id uuid NOT NULL,source_instance_id uuid NOT NULL,import_run_id uuid NOT NULL UNIQUE,
 UNIQUE(company_id,source_instance_id,import_run_id),FOREIGN KEY(company_id,source_instance_id,import_run_id) REFERENCES kristine.import_runs(company_id,source_instance_id,id));
CREATE TABLE kristine.company_rule_files (
 company_id uuid NOT NULL,source_instance_id uuid NOT NULL,import_run_id uuid NOT NULL,source_version_id uuid NOT NULL,source_path text NOT NULL CHECK(source_path IN ('_system/worktime-models.json','_system/schedule-models.json','_kristine/schedule-models.json')),
 PRIMARY KEY(import_run_id,source_path),
 FOREIGN KEY(company_id,source_instance_id,import_run_id) REFERENCES kristine.company_rule_runs(company_id,source_instance_id,import_run_id),
 FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id));
CREATE FUNCTION kristine.guard_company_rule_source() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM kristine.source_record_versions v JOIN kristine.source_records s ON s.company_id=v.company_id AND s.id=v.source_record_id
 WHERE v.company_id=NEW.company_id AND v.id=NEW.source_version_id AND s.entity_type='json_file_snapshot' AND s.external_id=NEW.source_path AND s.source_instance_id=NEW.source_instance_id)
 THEN RAISE EXCEPTION 'Company rule source mismatch';END IF;RETURN NEW;
END $$;
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.company_rule_files FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_source();
CREATE FUNCTION kristine.strict_source_number(v jsonb) RETURNS numeric LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN IF v IS NULL OR v='null'::jsonb THEN RETURN NULL;END IF;
 IF jsonb_typeof(v)<>'number' THEN RAISE EXCEPTION 'Source quantity must remain number';END IF;RETURN v::text::numeric;END $$;
CREATE VIEW kristine.latest_company_rule_runs AS
 SELECT DISTINCT ON(r.company_id,r.source_instance_id) r.company_id,r.source_instance_id,r.import_run_id
 FROM kristine.company_rule_runs r JOIN kristine.import_runs i ON i.id=r.import_run_id WHERE i.status='validated' ORDER BY r.company_id,r.source_instance_id,r.sequence DESC;
CREATE VIEW kristine.latest_company_rule_files AS SELECT f.* FROM kristine.latest_company_rule_runs l JOIN kristine.company_rule_files f USING(company_id,source_instance_id,import_run_id);
CREATE TABLE kristine.imported_company_rule_models (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),legacy_id text,name_original text,description_original text,rule_version_original text,payroll_reason_original text,project_time_source_original text,payroll_target_hours_weekday numeric,automatic_payroll_hours numeric,active_original boolean,system_protected_original boolean,office_model_original boolean,configured_original boolean,automatic_time_original boolean,PRIMARY KEY(source_version_id,model_position),UNIQUE(company_id,source_version_id,model_position),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id));
CREATE VIEW kristine.latest_company_rule_models AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_models e USING(company_id,source_version_id);
CREATE TABLE kristine.imported_company_rule_seasons (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),season_position integer NOT NULL CHECK(season_position>=0),raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),legacy_id text,name_original text,months_original jsonb,PRIMARY KEY(source_version_id,model_position,season_position),UNIQUE(company_id,source_version_id,model_position,season_position),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id),FOREIGN KEY(company_id,source_version_id,model_position) REFERENCES kristine.imported_company_rule_models(company_id,source_version_id,model_position));
CREATE VIEW kristine.latest_company_rule_seasons AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_seasons e USING(company_id,source_version_id);
CREATE TABLE kristine.imported_company_rule_weekdays (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),season_position integer NOT NULL CHECK(season_position>=0),weekday_key text NOT NULL,raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),from_original text,to_original text,lunch_break_minutes numeric,other_break_minutes numeric,target_hours numeric,payroll_target_hours numeric,free_original boolean,PRIMARY KEY(source_version_id,model_position,season_position,weekday_key),UNIQUE(company_id,source_version_id,model_position,season_position,weekday_key),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id),FOREIGN KEY(company_id,source_version_id,model_position,season_position) REFERENCES kristine.imported_company_rule_seasons(company_id,source_version_id,model_position,season_position));
CREATE VIEW kristine.latest_company_rule_weekdays AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_weekdays e USING(company_id,source_version_id);
CREATE TABLE kristine.imported_company_rule_blocks (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),block_key text NOT NULL,raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),label_original text,enabled_original boolean,PRIMARY KEY(source_version_id,model_position,block_key),UNIQUE(company_id,source_version_id,model_position,block_key),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id),FOREIGN KEY(company_id,source_version_id,model_position) REFERENCES kristine.imported_company_rule_models(company_id,source_version_id,model_position));
CREATE VIEW kristine.latest_company_rule_blocks AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_blocks e USING(company_id,source_version_id);
CREATE TABLE kristine.imported_company_rule_block_rows (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),block_key text NOT NULL,row_position integer NOT NULL CHECK(row_position>=0),raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),legacy_id text,from_original text,to_original text,lunch_from_original text,lunch_to_original text,pause_from_original text,pause_to_original text,activity_code_original text,activity_label_original text,days_original jsonb,PRIMARY KEY(source_version_id,model_position,block_key,row_position),UNIQUE(company_id,source_version_id,model_position,block_key,row_position),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id),FOREIGN KEY(company_id,source_version_id,model_position,block_key) REFERENCES kristine.imported_company_rule_blocks(company_id,source_version_id,model_position,block_key));
CREATE VIEW kristine.latest_company_rule_block_rows AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_block_rows e USING(company_id,source_version_id);
CREATE TABLE kristine.imported_company_rule_schedule_days (company_id uuid NOT NULL,source_version_id uuid NOT NULL,model_position integer NOT NULL CHECK(model_position>=0),day_position integer NOT NULL CHECK(day_position>=0),raw_payload jsonb NOT NULL CHECK(jsonb_typeof(raw_payload)='object'),day_name_original text,from_original text,to_original text,pause_start_original text,pause_end_original text,lunch_start_original text,lunch_end_original text,pause_minutes numeric,should_hours numeric,is_work_day_original boolean,PRIMARY KEY(source_version_id,model_position,day_position),UNIQUE(company_id,source_version_id,model_position,day_position),FOREIGN KEY(company_id,source_version_id) REFERENCES kristine.source_record_versions(company_id,id),FOREIGN KEY(company_id,source_version_id,model_position) REFERENCES kristine.imported_company_rule_models(company_id,source_version_id,model_position));
CREATE VIEW kristine.latest_company_rule_schedule_days AS SELECT e.*,f.source_instance_id,f.source_path,f.import_run_id AS reconciliation_run_id FROM kristine.latest_company_rule_files f JOIN kristine.imported_company_rule_schedule_days e USING(company_id,source_version_id);
CREATE FUNCTION kristine.guard_company_rule_entry() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p text;BEGIN
 SELECT s.external_id INTO p FROM kristine.source_record_versions v JOIN kristine.source_records s ON s.company_id=v.company_id AND s.id=v.source_record_id WHERE v.company_id=NEW.company_id AND v.id=NEW.source_version_id AND s.entity_type='json_file_snapshot';
 IF p IS NULL OR p NOT IN ('_system/worktime-models.json','_system/schedule-models.json','_kristine/schedule-models.json')
 OR (TG_TABLE_NAME='imported_company_rule_schedule_days' AND p='_system/worktime-models.json')
 OR (TG_TABLE_NAME IN ('imported_company_rule_seasons','imported_company_rule_weekdays','imported_company_rule_blocks','imported_company_rule_block_rows') AND p<>'_system/worktime-models.json')
 THEN RAISE EXCEPTION 'Company rule entry source mismatch';END IF;RETURN NEW;END $$;
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.company_rule_runs FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.company_rule_runs FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.company_rule_files FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.company_rule_files FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_models FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_models FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_models FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_seasons FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_seasons FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_seasons FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_weekdays FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_weekdays FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_weekdays FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_blocks FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_blocks FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_blocks FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_block_rows FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_block_rows FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_block_rows FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON kristine.imported_company_rule_schedule_days FOR EACH ROW EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER no_truncate BEFORE TRUNCATE ON kristine.imported_company_rule_schedule_days FOR EACH STATEMENT EXECUTE FUNCTION kristine.reject_history_change();
CREATE TRIGGER source_guard BEFORE INSERT ON kristine.imported_company_rule_schedule_days FOR EACH ROW EXECUTE FUNCTION kristine.guard_company_rule_entry();
COMMIT;
