'use strict';
const {createHash}=require('node:crypto');const {isDeepStrictEqual}=require('node:util');
const hash=s=>createHash('sha256').update(s).digest('hex');
const text=v=>{if(v==null)return null;if(typeof v!=='string')throw Error('Task field must be text');return v||null;};
const date=v=>{v=text(v);if(v&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||new Date(v).toISOString().slice(0,10)!==v))throw Error('Invalid task date');return v;};
const stamp=v=>{v=text(v);if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/.test(v))return null;const d=new Date(v);if(!Number.isFinite(d.getTime()))throw Error('Invalid timestamp');return d.toISOString();};
const time=v=>{v=text(v);if(v&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw Error('Invalid appointment time');return v?v+':00':null;};
function prepareTasks(originalText){const rows=JSON.parse(originalText);if(!Array.isArray(rows))throw Error('Tasks must be array');const ids=new Set();return rows.map(raw=>{
 const id=text(raw.id),title=text(raw.title);if(!id||ids.has(id))throw Error('Invalid/duplicate task ID');ids.add(id);if(!title?.trim())throw Error('Missing task title');
 const type={Freigabe:'approval',Sonstiges:'other','Rückruf':'callback',Angebot:'offer',Termin:'appointment',Problem:'problem',Reklamation:'complaint'}[raw.taskType];const priority={normal:'normal',heute:'today',sofort:'immediate'}[raw.priority];if(!type||!priority||!['open','done','in_progress','cancelled'].includes(raw.status))throw Error('Unknown task state');
 const created=stamp(raw.createdAt),completed=stamp(raw.completedAt),reasons=[];if(!created)reasons.push('created_timezone_missing');if(raw.completedAt&&!completed)reasons.push('completed_timezone_missing');
 let appointment=null;if(raw.appointment){const a=raw.appointment;appointment={appointment_date:date(a.date),starts_local:time(a.from),ends_local:time(a.to),calendar_owner:text(a.calendarOwner),calendar_account:text(a.calendarAccount)};if(!appointment.appointment_date||!appointment.starts_local||(appointment.ends_local&&appointment.ends_local<appointment.starts_local))throw Error('Incomplete appointment');}
 return {id,raw,originalText:JSON.stringify(raw),title,task_type:type,priority,status:raw.status,due_on:date(raw.dueDate),created,completed,reasons,appointment};
});}
async function importTasks(pool,{companyId,sourceInstanceId,originalText}){const rows=prepareTasks(originalText);const c=await pool.connect();let begun=false;try{
 await c.query('BEGIN');begun=true;if((await c.query('SELECT id FROM kristine.source_instances WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,sourceInstanceId])).rows.length!==1)throw Error('Source/company mismatch');
 const mappings=(await c.query('SELECT s.entity_type,s.external_id,x.employee_id,x.project_id FROM kristine.source_records s JOIN kristine.external_references x ON x.source_record_id=s.id AND x.company_id=s.company_id WHERE s.company_id=$1 AND s.source_instance_id=$2',[companyId,sourceInstanceId])).rows;const employees=new Map(mappings.filter(x=>x.entity_type==='employee'&&x.employee_id).map(x=>[x.external_id,x.employee_id])),projects=new Map(mappings.filter(x=>x.entity_type==='project'&&x.project_id).map(x=>[x.external_id,x.project_id]));
 const run=(await c.query('INSERT INTO kristine.import_runs(company_id,source_instance_id,manifest_sha256) VALUES($1,$2,$3) RETURNING id',[companyId,sourceInstanceId,hash(originalText)])).rows[0].id;
 const record=async(type,id)=>(await c.query('INSERT INTO kristine.source_records(company_id,source_instance_id,entity_type,external_id) VALUES($1,$2,$3,$4) ON CONFLICT(company_id,source_instance_id,entity_type,external_id) DO UPDATE SET external_id=EXCLUDED.external_id RETURNING id',[companyId,sourceInstanceId,type,id])).rows[0].id;
 const archive=async(sid,s)=>{const old=(await c.query('SELECT original_text,source_sha256,raw_payload FROM kristine.source_record_versions WHERE source_record_id=$1',[sid])).rows;if(old.length){if(old.length!==1||old[0].original_text!==s||old[0].source_sha256!==hash(s)||!isDeepStrictEqual(old[0].raw_payload,JSON.parse(s)))throw Error('Task source changed; review required');return;}await c.query('INSERT INTO kristine.source_record_versions(company_id,source_instance_id,source_record_id,import_run_id,raw_payload,original_text,source_sha256) VALUES($1,$2,$3,$4,$5,$6,$7)',[companyId,sourceInstanceId,sid,run,s,s,hash(s)]);};
 await archive(await record('task_file','_kristine/tasks.json'),originalText);const result={created:0,unchanged:0,assignments:0,appointments:0,review:0,verified:0};
 for(const r of rows){const raw=r.raw,creator=text(raw.creatorId),assignee=text(raw.assigneeId),job=text(raw.jobId);const creatorId=employees.get(creator)||null,assigneeId=employees.get(assignee)||null,projectId=projects.get(job)||null;const reasons=[...r.reasons];if(creator&&!creatorId)reasons.push('creator_not_employee');if(assignee&&!assigneeId)reasons.push('assignee_unresolved');if(job&&!projectId)reasons.push('project_unresolved');if(raw.visitProtocol)reasons.push('visit_protocol_archived_pending_normalization');if(raw.customerMaster||raw.projectContacts)reasons.push('contact_snapshot_archived_pending_normalization');
 const expected={project_id:projectId,title:r.title,task_type:r.task_type,priority:r.priority,status:r.status,due_on:r.due_on,creator_employee_id:creatorId,creator_name_snapshot:text(raw.creatorName),legacy_assignee_name:text(raw.assigneeName),contact_name_snapshot:text(raw.contactName),contact_phone_snapshot:text(raw.contactPhone),contact_email_snapshot:text(raw.contactEmail),note:text(raw.reminder),completed_at:r.completed,legacy_creator_id:creator,legacy_assignee_id:assignee,legacy_project_id:job,import_review_reasons:reasons};
 const sid=await record('task',r.id);const refs=(await c.query('SELECT task_id FROM kristine.external_references WHERE company_id=$1 AND source_record_id=$2',[companyId,sid])).rows;let tid;
 if(refs.length){tid=refs[0].task_id;if(!tid)throw Error('Task mapping conflict');await archive(sid,r.originalText);result.unchanged++;}
 else{if((await c.query('SELECT 1 FROM kristine.source_record_versions WHERE source_record_id=$1',[sid])).rows.length)throw Error('Task mapping missing');const fields=Object.keys(expected),values=Object.values(expected);if(r.created){fields.push('created_at');values.push(r.created);}tid=(await c.query('INSERT INTO kristine.tasks(company_id,'+fields.join(',')+') VALUES('+[companyId,...values].map((_,i)=>'$'+(i+1)).join(',')+') RETURNING id',[companyId,...values])).rows[0].id;await c.query('INSERT INTO kristine.external_references(company_id,source_record_id,task_id) VALUES($1,$2,$3)',[companyId,sid,tid]);await archive(sid,r.originalText);
 if(assigneeId){await c.query('INSERT INTO kristine.task_assignments(company_id,task_id,employee_id) VALUES($1,$2,$3)',[companyId,tid,assigneeId]);result.assignments++;}if(r.appointment){const a=r.appointment;await c.query('INSERT INTO kristine.task_local_appointments(company_id,task_id,appointment_date,starts_local,ends_local,calendar_owner,calendar_account) VALUES($1,$2,$3,$4,$5,$6,$7)',[companyId,tid,...Object.values(a)]);result.appointments++;}result.created++;}
 const actual=(await c.query('SELECT '+Object.keys(expected).join(',')+(r.created?',created_at':'')+' FROM kristine.tasks WHERE company_id=$1 AND id=$2',[companyId,tid])).rows[0];for(const k of ['completed_at','created_at'])if(actual[k] instanceof Date)actual[k]=actual[k].toISOString();if(actual.due_on instanceof Date)actual.due_on=actual.due_on.toISOString().slice(0,10);if(r.created)expected.created_at=r.created;if(!isDeepStrictEqual(actual,expected))throw Error('Task field verification failed');
 const assignments=(await c.query('SELECT employee_id FROM kristine.task_assignments WHERE company_id=$1 AND task_id=$2 AND released_at IS NULL',[companyId,tid])).rows;if(!isDeepStrictEqual(assignments,assigneeId?[{employee_id:assigneeId}]:[]))throw Error('Task assignment verification failed');const appointments=(await c.query('SELECT appointment_date,starts_local,ends_local,calendar_owner,calendar_account FROM kristine.task_local_appointments WHERE company_id=$1 AND task_id=$2',[companyId,tid])).rows;for(const a of appointments)if(a.appointment_date instanceof Date)a.appointment_date=a.appointment_date.toISOString().slice(0,10);if(!isDeepStrictEqual(appointments,r.appointment?[r.appointment]:[]))throw Error('Task appointment verification failed');const events=(await c.query('SELECT e.snapshot=to_jsonb(t) AS matches FROM kristine.task_events e JOIN kristine.tasks t ON t.id=e.task_id AND t.company_id=e.company_id WHERE e.company_id=$1 AND e.task_id=$2 AND e.revision=1',[companyId,tid])).rows;if(events.length!==1||events[0].matches!==true)throw Error('Task snapshot verification failed');if(reasons.length)result.review++;result.verified++;
 }
 await c.query("UPDATE kristine.import_runs SET status='validated',finished_at=clock_timestamp() WHERE id=$1",[run]);await c.query('COMMIT');begun=false;return result;
 }catch(e){if(begun)await c.query('ROLLBACK');throw e;}finally{c.release();}}
module.exports={prepareTasks,importTasks};
